# Generated by Django 5.0.7 on 2024-07-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("national_currency_name", models.CharField(max_length=50)),
                ("national_currency_symbol", models.CharField(max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name="category",
            old_name="type_of_account",
            new_name="type_of_category",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_from",
                to="bank.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_to",
                to="bank.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_name",
                to="bank.category",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="service_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bank.category",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bank.country"
            ),
        ),
    ]
